version: '3.8'

services:
  
  backend:
    container_name: fastapi-app
    restart: always
    build: .
    ports:
      - "80:80"
    networks:
      - fastapi-mongo
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - mongo-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: UsersDB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - fastapi-mongo
      - mongo-network

networks:
  fastapi-mongo:
   name: fastapi-mongo

  mongo-network:
   name: mongo-network